apiVersion: v1
kind: Pod
metadata:
  name: nodejs
spec:
  containers:
  - name: web
    env:
      - name: test
        value: hello
      - name: from-secret
        valueFrom:
            secretKeyRef:
              key: hello
              name: big-secret